// array of mathematical formulas with their explanations
var formulas = [
    { name: "Pythagorean Theorem", formula: "a² + b² = c²", explanation: "The Pythagorean theorem states that in a right-angled triangle, the square of the length of the hypotenuse ('c') is equal to the sum of the squares of the lengths of the other two sides ('a' and 'b')." },
     { name: "Quadratic Formula", formula: "x = (-b ± √(b² - 4ac)) / 2a", explanation: "The quadratic formula gives the solutions of the quadratic equation ax² + bx + c = 0, where a, b, and c are constants, and 'x' represents the unknown variable." },
  { name: "Area of a Circle", formula: "A = πr²", explanation: "The area 'A' of a circle with radius 'r' is given by the formula πr², where π is a mathematical constant approximately equal to 3.14159." },
  { name: "Volume of a Sphere", formula: "V = (4/3)πr³", explanation: "The volume 'V' of a sphere with radius 'r' is given by the formula (4/3)πr³, where π is a mathematical constant approximately equal to 3.14159." },
  { name: "Sum of an Arithmetic Series", formula: "S = (n/2)(a₁ + aₙ)", explanation: "The sum 'S' of an arithmetic series with 'n' terms, where the first term is 'a₁' and the last term is 'aₙ', is given by the formula (n/2)(a₁ + aₙ)." },
  { name: "Sum of a Geometric Series", formula: "S = a(1 - rⁿ) / (1 - r)", explanation: "The sum 'S' of a geometric series with 'n' terms, where 'a' is the first term and 'r' is the common ratio, is given by the formula a(1 - rⁿ) / (1 - r)." },
  { name: "Mean of a Data Set", formula: "μ = Σx / n", explanation: "The mean 'μ' of a data set is calculated by adding up all the values 'x' and dividing by the total number of values 'n'." },
  { name: "Standard Deviation", formula: "σ = √((Σ(x - μ)²) / n)", explanation: "The standard deviation 'σ' of a data set is a measure of the amount of variation or dispersion among a set of values. It is calculated as the square root of the average of the squared differences between each value and the mean." },
  { name: "Distance Formula", formula: "d = √((x₂ - x₁)² + (y₂ - y₁)²)", explanation: "The distance 'd' between two points with coordinates (x₁, y₁) and (x₂, y₂) in a two-dimensional Cartesian plane is given by the formula √((x₂ - x₁)² + (y₂ - y₁)²)." },
  { name: "Binomial Theorem", formula: "(a + b)ⁿ = Σ(n choose k) * a^(n-k) * b^k", explanation: "The binomial theorem gives the expansion of powers of a binomial. It states that for any positive integer 'n', the expansion of (a + b)ⁿ is equal to the sum of n choose k multiplied by 'a' raised to the power of (n - k) and 'b' raised to the power of 'k', where k ranges from 0 to n." },
  { name: "Law of Sines", formula: "sin(A)/a = sin(B)/b = sin(C)/c", explanation: "The law of sines relates the sides and angles of a triangle. For any triangle, the ratio of the length of a side to the sine of its opposite angle is constant for all three sides." },
  { name: "Law of Cosines", formula: "c² = a² + b² - 2ab * cos(C)", explanation: "The law of cosines relates the lengths of the sides of a triangle to the cosine of one of its angles. It can be used to find the length of any side of a triangle when the lengths of the other two sides and the included angle are known." },
  { name: "Volume of a Cone", formula: "V = (1/3)πr²h", explanation: "The volume 'V' of a cone with radius 'r' and height 'h' is given by the formula (1/3)πr²h, where π is a mathematical constant approximately equal to 3.14159." },
  { name: "Sum of the Interior Angles of a Polygon", formula: "S = (n - 2) * 180°", explanation: "The sum 'S' of the interior angles of a polygon with 'n' sides is given by the formula (n - 2) * 180°. This formula applies to all polygons, regardless of the number of sides." },
  { name: "Law of Tangents", formula: "(a - b) / (a + b) = tan((A - B) / 2) / tan((A + B) / 2)", explanation: "The law of tangents relates the tangents of half the differences and half the sums of the angles of a triangle to the tangents of half the differences and half the sums of the sides opposite those angles." },
  { name: "Taylor Series Expansion", formula: "f(x) = f(a) + f'(a)(x - a) + (f''(a) / 2!)(x - a)² + (f'''(a) / 3!)(x - a)³ + ...", explanation: "The Taylor series expansion represents a function as an infinite sum of terms. It allows functions to be approximated by polynomials, which is useful for numerical calculations and solving differential equations." },
  { name: "Law of Exponents", formula: "a^m * a^n = a^(m+n)", explanation: "The law of exponents states that when multiplying two powers with the same base, the exponents are added together. For example, a^m * a^n = a^(m+n)." },
  { name: "Fibonacci Sequence", formula: "F(n) = F(n-1) + F(n-2), F(0) = 0, F(1) = 1", explanation: "The Fibonacci sequence is a series of numbers in which each number is the sum of the two preceding ones, usually starting with 0 and 1. The sequence begins: 0, 1, 1, 2, 3, 5, 8, 13, 21, 34, ... and continues indefinitely." },
  { name: "Volume of a Cylinder", formula: "V = πr²h", explanation: "The volume 'V' of a cylinder with radius 'r' and height 'h' is given by the formula πr²h, where π is a mathematical constant approximately equal to 3.14159." },
  { name: "Area of a Triangle", formula: "A = (1/2) * base * height", explanation: "The area 'A' of a triangle with base 'b' and height 'h' is given by the formula (1/2) * base * height." },
  { name: "Euler's Formula", formula: "V - E + F = 2", explanation: "Euler's formula relates the number of vertices ('V'), edges ('E'), and faces ('F') of a convex polyhedron. It states that for any convex polyhedron, the number of vertices minus the number of edges plus the number of faces equals 2." },
  { name: "Volume of a Cube", formula: "V = s³", explanation: "The volume 'V' of a cube with side length 's' is given by the formula s³, where 's' is the length of one side of the cube." },
  { name: "Area of a Rectangle", formula: "A = length * width", explanation: "The area 'A' of a rectangle with length 'l' and width 'w' is given by the formula length * width." },
  { name: "Surface Area of a Sphere", formula: "A = 4πr²", explanation: "The surface area 'A' of a sphere with radius 'r' is given by the formula 4πr², where π is a mathematical constant approximately equal to 3.14159." },
  { name: "Fundamental Theorem of Calculus", formula: "∫(a to b) f(x) dx = F(b) - F(a)", explanation: "The fundamental theorem of calculus establishes a relationship between differentiation and integration. It states that if 'F(x)' is an antiderivative of 'f(x)' on the interval [a, b], then the definite integral of 'f(x)' from 'a' to 'b' is equal to 'F(b) - F(a)'." },
  { name: "Volume of a Cone (Frustum)", formula: "V = (1/3)πh(h₁² + h₂² + h₁h₂)", explanation: "The volume 'V' of a cone frustum (the portion of a cone between two parallel planes cutting it) with heights 'h₁' and 'h₂' is given by the formula (1/3)πh(h₁² + h₂² + h₁h₂), where 'h' is the height of the frustum." },
  { name: "Surface Area of a Cone", formula: "A = πrl + πr²", explanation: "The surface area 'A' of a cone with slant height 'l' and radius 'r' is given by the formula πrl + πr², where 'l' is the slant height and 'r' is the radius." },
  { name: "Sum of Squares Formula", formula: "Σx² = n(n + 1)(2n + 1) / 6", explanation: "The sum of squares formula provides a shortcut for finding the sum of the squares of the first 'n' positive integers. It states that the sum of the squares of the first 'n' positive integers is equal to n(n + 1)(2n + 1) / 6." },
  { name: "Perimeter of a Rectangle", formula: "P = 2(length + width)", explanation: "The perimeter 'P' of a rectangle with length 'l' and width 'w' is given by the formula 2(length + width)." },
  { name: "Heron's Formula (Triangle Area)", formula: "A = √(s(s - a)(s - b)(s - c))", explanation: "Heron's formula gives the area 'A' of a triangle when the lengths of its three sides 'a', 'b', and 'c' are known. Here, 's' represents the semiperimeter of the triangle, defined as (a + b + c) / 2." },
  { name: "Area of a Trapezoid", formula: "A = (1/2)(a + b)h", explanation: "The area 'A' of a trapezoid with parallel sides 'a' and 'b' and height 'h' is given by the formula (1/2)(a + b)h." },
  { name: "Mean Value Theorem", formula: "f'(c) = (f(b) - f(a)) / (b - a)", explanation: "The mean value theorem states that for a function 'f' continuous on the closed interval [a, b] and differentiable on the open interval (a, b), there exists at least one point 'c' in the interval (a, b) such that the derivative of 'f' at 'c' is equal to the average rate of change of 'f' over the interval [a, b]." },
  { name: "Surface Area of a Cylinder", formula: "A = 2πrh + 2πr²", explanation: "The surface area 'A' of a cylinder with radius 'r' and height 'h' is given by the formula 2πrh + 2πr², where 'r' is the radius and 'h' is the height." },
  { name: "Euler's Identity", formula: "e^(iπ) + 1 = 0", explanation: "Euler's identity is a remarkable equation that relates five fundamental mathematical constants: 'e' (the base of the natural logarithm), 'π' (pi, the ratio of a circle's circumference to its diameter), 'i' (the imaginary unit, √(-1)), 1, and 0. It is often hailed as one of the most beautiful equations in mathematics." },
  { name: "Volume of a Rectangular Prism", formula: "V = length * width * height", explanation: "The volume 'V' of a rectangular prism (also called a rectangular parallelepiped) with length 'l', width 'w', and height 'h' is given by the formula length * width * height." },
  { name: "Arc Length of a Circle", formula: "L = rθ", explanation: "The arc length 'L' of a circle with radius 'r' and central angle 'θ' (measured in radians) is given by the formula rθ." },
  { name: "Factorial", formula: "n! = n * (n - 1) * (n - 2) * ... * 3 * 2 * 1", explanation: "The factorial of a non-negative integer 'n', denoted by 'n!', is the product of all positive integers less than or equal to 'n'. For example, 5! = 5 * 4 * 3 * 2 * 1 = 120." },
  { name: "Area of a Parallelogram", formula: "A = base * height", explanation: "The area 'A' of a parallelogram with base 'b' and height 'h' is given by the formula base * height." },
  { name: "Volume of a Pyramid", formula: "V = (1/3) * base_area * height", explanation: "The volume 'V' of a pyramid with a polygonal base and height 'h' is given by the formula (1/3) * base_area * height, where 'base_area' is the area of the base." },
  { name: "Arc Length of a Curve", formula: "L = ∫(a to b) √(1 + (dy/dx)²) dx", explanation: "The arc length 'L' of a smooth curve defined by the function y = f(x) between two points 'a' and 'b' on the x-axis is given by the integral of √(1 + (dy/dx)²) with respect to 'x' over the interval [a, b]." },
  { name: "Law of Universal Gravitation", formula: "F = G * (m₁ * m₂) / r²", explanation: "The law of universal gravitation states that every point mass attracts every other point mass in the universe with a force that is directly proportional to the product of their masses and inversely proportional to the square of the distance between their centers." },
  { name: "Volume of a Tetrahedron", formula: "V = (1/6) * area_of_base * height", explanation: "The volume 'V' of a tetrahedron (a polyhedron with four triangular faces) with a triangular base and height 'h' is given by the formula (1/6) * area_of_base * height, where 'area_of_base' is the area of the triangular base." },
  { name: "Law of Large Numbers", formula: "lim(n → ∞) (X₁ + X₂ + ... + Xn) / n = μ", explanation: "The law of large numbers states that as the number of trials 'n' of a random experiment increases, the sample mean of the outcomes converges to the population mean 'μ'. In other words, the average of a large number of independent and identically distributed random variables approaches the expected value of the distribution." },
  { name: "Volume of a Prism", formula: "V = base_area * height", explanation: "The volume 'V' of a prism (a polyhedron with two parallel and congruent polygonal bases connected by rectangles) with a base area 'A' and height 'h' is given by the formula base_area * height." },
  { name: "Sum of Geometric Series", formula: "S = a * (1 - rⁿ) / (1 - r)", explanation: "The sum 'S' of a geometric series with 'n' terms, where 'a' is the first term and 'r' is the common ratio, is given by the formula a * (1 - rⁿ) / (1 - r)." },
  { name: "Probability Mass Function (Discrete)", formula: "P(X = x) = f(x)", explanation: "The probability mass function (PMF) of a discrete random variable 'X' gives the probability that 'X' is equal to a particular value 'x'. It is denoted by 'P(X = x)' or 'f(x)', where 'f(x)' represents the probability of the outcome 'x'." },
  { name: "Surface Area of a Prism", formula: "A = 2 * base_area + perimeter_of_base * height", explanation: "The surface area 'A' of a prism (a polyhedron with two parallel and congruent polygonal bases connected by rectangles) with a base area 'A' and height 'h' is given by the formula 2 * base_area + perimeter_of_base * height." },
  { name: "Binomial Coefficient", formula: "n choose k = n! / (k!(n - k)!)", explanation: "The binomial coefficient 'n choose k' represents the number of ways to choose 'k' elements from a set of 'n' elements without regard to the order. It is calculated using the factorial function." },
  { name: "Volume of a Cylinder (Frustum)", formula: "V = (1/3) * π * (R² + r² + (R * r)) * h", explanation: "The volume 'V' of a cylinder frustum (the portion of a cylinder between two parallel planes cutting it) with radii 'R' and 'r' at the ends and height 'h' is given by the formula (1/3) * π * (R² + r² + (R * r)) * h." },
  { name: "Probability Density Function (Continuous)", formula: "P(a ≤ X ≤ b) = ∫(a to b) f(x) dx", explanation: "The probability density function (PDF) of a continuous random variable 'X' gives the probability that 'X' falls within a particular interval [a, b]. It is denoted by 'P(a ≤ X ≤ b)' or 'f(x)', where 'f(x)' represents the density of the distribution." },
  { name: "Volume of a Prism (Frustum)", formula: "V = (1/3) * (A₁ + A₂ + √(A₁ * A₂)) * h", explanation: "The volume 'V' of a prism frustum (the portion of a prism between two parallel planes cutting it) with areas 'A₁' and 'A₂' at the ends and height 'h' is given by the formula (1/3) * (A₁ + A₂ + √(A₁ * A₂)) * h." },
  { name: "Expectation of a Random Variable", formula: "E(X) = Σ(x * P(X = x))", explanation: "The expectation or expected value 'E(X)' of a random variable 'X' is a measure of the center of its distribution. It is calculated as the sum of the products of each possible value of 'X' and its corresponding probability." },
  { name: "Angle Sum Identity (Sine)", formula: "sin(A + B) = sin(A) * cos(B) + cos(A) * sin(B)", explanation: "The angle sum identity for the sine function relates the sine of the sum of two angles 'A' and 'B' to the sines and cosines of the individual angles. It is a fundamental trigonometric identity." },
  { name: "Angle Sum Identity (Cosine)", formula: "cos(A + B) = cos(A) * cos(B) - sin(A) * sin(B)", explanation: "The angle sum identity for the cosine function relates the cosine of the sum of two angles 'A' and 'B' to the cosines and sines of the individual angles. It is a fundamental trigonometric identity." },
  { name: "Angle Sum Identity (Tangent)", formula: "tan(A + B) = (tan(A) + tan(B)) / (1 - tan(A) * tan(B))", explanation: "The angle sum identity for the tangent function relates the tangent of the sum of two angles 'A' and 'B' to the tangents of the individual angles. It is a fundamental trigonometric identity." },
  { name: "Volume of a Sphere (Segment)", formula: "V = (1/3) * π * h² * (3R - h)", explanation: "The volume 'V' of a spherical segment (the portion of a sphere cut off by a plane) with height 'h' and radius 'R' is given by the formula (1/3) * π * h² * (3R - h)." },
  { name: "Curvature of a Curve", formula: "κ = |dθ/ds|", explanation: "The curvature 'κ' of a curve measures how much the curve deviates from a straight line at a particular point. It is defined as the absolute value of the rate of change of the tangent angle 'θ' with respect to arc length 's'." },
  { name: "Taylor Series Expansion (Multivariable)", formula: "f(x, y) ≈ f(a, b) + (∂f/∂x)(a, b)(x - a) + (∂f/∂y)(a, b)(y - b)", explanation: "The multivariable Taylor series expansion approximates a function 'f(x, y)' near a point (a, b) as a sum of terms involving partial derivatives of 'f' evaluated at (a, b) and powers of the differences (x - a) and (y - b)." },
  { name: "Fréchet Derivative", formula: "L(f; x, h) = lim(ε → 0) (f(x + εh) - f(x)) / ε", explanation: "The Fréchet derivative of a function 'f' at a point 'x' in the direction 'h' is a generalization of the derivative for Banach spaces. It measures the rate of change of 'f' at 'x' in the direction 'h', accounting for variations in the norm of 'h'." },
  { name: "Navier-Stokes Equations", formula: "ρ(dv/dt) = -∇P + μ∇²v + ρg", explanation: "The Navier-Stokes equations describe the motion of fluid substances. They are a set of partial differential equations that govern the conservation of momentum for an incompressible fluid under the influence of external forces." },
  { name: "Laplace Transform", formula: "F(s) = ∫(0 to ∞) e^(-st) f(t) dt", explanation: "The Laplace transform is an integral transform that converts a function of time 't' into a function of a complex variable 's'. It is widely used to solve differential equations and analyze systems in engineering and physics." },
  { name: "Fourier Transform", formula: "F(ω) = ∫(-∞ to ∞) f(t) e^(-iωt) dt", explanation: "The Fourier transform is an integral transform that decomposes a function of time 't' into its frequency components. It is used in signal processing, image analysis, and many other fields to analyze and process signals and data." },
  { name: "Black-Scholes Formula", formula: "C = S₀N(d₁) - Xe^(-rt)N(d₂)", explanation: "The Black-Scholes formula is used to calculate the theoretical price of a European call or put option on a non-dividend-paying stock. It takes into account factors such as the stock price ('S₀'), the strike price ('X'), the risk-free interest rate ('r'), the time to expiration ('t'), and the volatility of the stock ('σ')." },
  { name: "Euler-Lagrange Equation", formula: "d/dt(∂L/∂(dq/dt)) - ∂L/∂q = 0", explanation: "The Euler-Lagrange equation is a differential equation that arises in the calculus of variations. It is used to find the functions that extremize certain functionals, such as the action integral in classical mechanics." },
  { name: "Stirling's Approximation", formula: "n! ≈ √(2πn)(n/e)ⁿ", explanation: "Stirling's approximation is an asymptotic formula for the factorial function 'n!'. It provides an estimate of 'n!' for large values of 'n' and is derived using the Gamma function and the method of stationary phase." },
  { name: "Gaussian Integral", formula: "∫(-∞ to ∞) e^(-x²) dx = √π", explanation: "The Gaussian integral is an important integral in probability theory, statistics, and physics. It evaluates the integral of the Gaussian function e^(-x²) over the entire real line and yields the square root of π." },
  { name: "Cauchy's Integral Formula", formula: "f(a) = (1/(2πi)) ∫(C) f(z)/(z - a) dz", explanation: "Cauchy's integral formula relates the values of a holomorphic function 'f(z)' at points inside a simple closed contour 'C' to its values on the boundary of 'C'. It plays a central role in complex analysis and the theory of analytic functions." },
  { name: "Residue Theorem", formula: "∮(C) f(z) dz = 2πi ∑ Res(f, zᵢ)", explanation: "The residue theorem provides a method for evaluating contour integrals of meromorphic functions with poles inside a closed contour 'C'. It states that the integral of a function 'f(z)' around 'C' is equal to 2πi times the sum of the residues of 'f(z)' at its isolated singularities inside 'C'." },
  { name: "Gamma Function", formula: "Γ(z) = ∫(0 to ∞) t^(z-1) e^(-t) dt", explanation: "The gamma function is a generalization of the factorial function to complex numbers. It is defined for all complex numbers except non-positive integers and evaluates to the factorial of (z - 1) for positive integers 'z'. The gamma function plays a key role in probability theory, statistics, and various areas of mathematics." },
  { name: "Bessel Function", formula: "Jₙ(x) = (1/π) ∫(0 to π) cos(nθ - xsinθ) dθ", explanation: "Bessel functions are a family of solutions to Bessel's differential equation, which arises in many problems of mathematical physics, particularly those involving cylindrical or spherical symmetry. They are named after the mathematician Friedrich Bessel." },
  { name: "Legendre Polynomials", formula: "Pₙ(x) = (1/2ⁿn!) dⁿ/dxⁿ(x² - 1)ⁿ", explanation: "Legendre polynomials are a family of orthogonal polynomials that arise in the solution of Laplace's equation in spherical coordinates and various other problems in physics and engineering. They are named after the mathematician Adrien-Marie Legendre." },
  { name: "Dirac Delta Function", formula: "δ(x) = { +∞, x = 0; 0, x ≠ 0 }", explanation: "The Dirac delta function, or impulse function, is a generalized function that is zero everywhere except at the origin, where it is infinitely tall and its integral over the entire real line is equal to one. It is widely used in physics and engineering to model point-like sources or idealized impulses." },
  { name: "Gauss's Law", formula: "∮(S) E ⋅ dA = Q / ε₀", explanation: "Gauss's law relates the electric flux through a closed surface 'S' to the charge enclosed by the surface. It states that the electric flux is equal to the total charge divided by the electric constant ε₀, also known as the permittivity of free space." },
  { name: "Ampère's Law", formula: "∮(C) B ⋅ dl = μ₀I_enc", explanation: "Ampère's law relates the magnetic field around a closed loop 'C' to the electric current passing through any surface bounded by 'C'. It states that the integral of the magnetic field around a closed loop is equal to the permeability of free space μ₀ times the total electric current passing through any surface bounded by the loop." },
  { name: "Faraday's Law of Induction", formula: "ε = -dΦ/dt", explanation: "Faraday's law of electromagnetic induction describes how a changing magnetic field induces an electromotive force (emf) in a nearby conductor. It states that the induced emf is equal to the negative rate of change of the magnetic flux through a surface bounded by the conductor." },
  { name: "Poisson Distribution", formula: "P(X = k) = (λ^k * e^(-λ)) / k!", explanation: "The Poisson distribution describes the probability of a given number of events occurring in a fixed interval of time or space if these events occur with a known constant mean rate and are independent of the time since the last event." },
  { name: "Maxwell's Equations", formula: "∇ ⋅ E = ρ / ε₀, ∇ ⋅ B = 0, ∇ × E = -∂B/∂t, ∇ × B = μ₀J + μ₀ε₀ ∂E/∂t", explanation: "Maxwell's equations are a set of four fundamental equations that describe how electric and magnetic fields interact with matter and with each other. They form the basis of classical electromagnetism and predict the behavior of electromagnetic waves." },
  { name: "Coulomb's Law", formula: "F = k * (|q₁q₂| / r²)", explanation: "Coulomb's law describes the electrostatic force between two charged particles. It states that the force between two point charges is directly proportional to the product of their magnitudes and inversely proportional to the square of the distance between them." },
  { name: "Newton's Second Law of Motion", formula: "F = ma", explanation: "Newton's second law of motion states that the acceleration of an object is directly proportional to the net force acting on it and inversely proportional to its mass. It is expressed mathematically as F = ma, where 'F' is the net force acting on the object, 'm' is its mass, and 'a' is its acceleration." },
  { name: "Newton's Law of Universal Gravitation", formula: "F = G * (m₁ * m₂) / r²", explanation: "Newton's law of universal gravitation states that every point mass attracts every other point mass in the universe with a force that is directly proportional to the product of their masses and inversely proportional to the square of the distance between their centers." },
  { name: "Einstein's Mass-Energy Equivalence", formula: "E = mc²", explanation: "Einstein's mass-energy equivalence formula, E = mc², states that the energy 'E' of an object is equal to its mass 'm' multiplied by the speed of light 'c' squared. This equation describes the relationship between mass and energy and is a fundamental principle of modern physics." },
  { name: "Planck-Einstein Relation", formula: "E = hf", explanation: "The Planck-Einstein relation relates the energy 'E' of a photon to its frequency 'f'. It states that the energy of a photon is directly proportional to its frequency, with the proportionality constant being Planck's constant 'h'." },
  { name: "Heisenberg Uncertainty Principle", formula: "Δx * Δp ≥ ħ / 2", explanation: "The Heisenberg uncertainty principle states that there is a fundamental limit to the precision with which certain pairs of physical properties, such as position and momentum, can be simultaneously known. Mathematically, it is expressed as Δx * Δp ≥ ħ / 2, where Δx is the uncertainty in position, Δp is the uncertainty in momentum, and ħ is the reduced Planck constant." },
  { name: "Schrödinger Equation", formula: "iħ ∂ψ/∂t = -ħ²/(2m) ∇²ψ + Vψ", explanation: "The Schrödinger equation is a fundamental equation in quantum mechanics that describes how the quantum state of a physical system changes over time. It is a partial differential equation that relates the time derivative of the wave function 'ψ' to its spatial derivatives and the potential energy 'V'." },
  { name: "Euler's Formula (Polyhedra)", formula: "V - E + F = 2", explanation: "Euler's formula relates the number of vertices ('V'), edges ('E'), and faces ('F') of a convex polyhedron. It states that for any convex polyhedron, the number of vertices minus the number of edges plus the number of faces equals 2." },
  { name: "Euler's Formula (Graph Theory)", formula: "V - E + F = 1", explanation: "Euler's formula in graph theory relates the number of vertices ('V'), edges ('E'), and faces ('F') of a planar graph. It states that for any connected planar graph drawn without intersecting edges, the number of vertices minus the number of edges plus the number of faces equals 1." },
  { name: "Fermat's Last Theorem", formula: "xⁿ + yⁿ ≠ zⁿ for n > 2", explanation: "Fermat's Last Theorem states that there are no three positive integers 'x', 'y', and 'z' that satisfy the equation xⁿ + yⁿ = zⁿ for any integer value of 'n' greater than 2. This theorem, proposed by Pierre de Fermat in 1637, remained unproven for over 350 years until it was finally proved by Andrew Wiles in 1994." },
  { name: "Pythagorean Theorem", formula: "a² + b² = c²", explanation: "The Pythagorean theorem states that in a right-angled triangle, the square of the length of the hypotenuse ('c') is equal to the sum of the squares of the lengths of the other two sides ('a' and 'b'). It is one of the most famous and widely used theorems in mathematics." },
  { name: "Euclidean Algorithm", formula: "gcd(a, b) = gcd(b, a % b)", explanation: "The Euclidean algorithm is an efficient method for computing the greatest common divisor (GCD) of two integers 'a' and 'b'. It repeatedly applies the principle that the GCD of 'a' and 'b' is equal to the GCD of 'b' and the remainder of 'a' divided by 'b' until the remainder is zero." },
  { name: "Binomial Theorem", formula: "(a + b)ⁿ = Σ(k = 0 to n) (n choose k) * a^(n - k) * b^k", explanation: "The binomial theorem provides a formula for expanding powers of binomials. It states that the nth power of the sum of two terms 'a' and 'b' is equal to the sum of the binomial coefficients times 'a' raised to the power of (n - k) times 'b' raised to the power of 'k', summed over all values of 'k' from 0 to 'n'." },
  { name: "Law of Cosines", formula: "c² = a² + b² - 2ab * cos(C)", explanation: "The law of cosines relates the lengths of the sides of a triangle to the cosine of one of its angles. It is a generalization of the Pythagorean theorem and is used to find the length of a side of a triangle when the lengths of the other sides and the measure of an angle between them are known." },
  { name: "Law of Sines", formula: "a/sin(A) = b/sin(B) = c/sin(C)", explanation: "The law of sines relates the lengths of the sides of a triangle to the sines of its angles. It states that the ratio of the length of a side of a triangle to the sine of the angle opposite that side is constant for all three sides of the triangle." },
  { name: "Quadratic Formula", formula: "x = (-b ± √(b² - 4ac)) / (2a)", explanation: "The quadratic formula provides the solutions to the quadratic equation ax² + bx + c = 0, where 'a', 'b', and 'c' are constants with 'a' ≠ 0, and 'x' represents the variable. It is derived using the method of completing the square." },
  { name: "Fundamental Theorem of Arithmetic", formula: "Every integer greater than 1 either is a prime number itself or can be represented as the product of prime numbers and that, moreover, this representation is unique, up to (except for) the order of the factors.", explanation: "The Fundamental Theorem of Arithmetic states that every integer greater than 1 either is a prime number itself or can be represented as the product of prime numbers, and that this representation is unique, up to the order of the factors. This theorem is fundamental in number theory and is used in various mathematical proofs and applications." },
  { name: "Mean Value Theorem for Integrals", formula: "If a function 'f' is continuous on the closed interval [a, b], then there exists at least one number 'c' in the interval (a, b) such that the average value of 'f' on the interval [a, b] is equal to 'f(c)'.", explanation: "The Mean Value Theorem for Integrals states that if a function 'f' is continuous on the closed interval [a, b], then there exists at least one number 'c' in the interval (a, b) such that the average value of 'f' on the interval [a, b] is equal to 'f(c)'. This theorem is a fundamental result in calculus and is used in various applications, including finding the center of mass and calculating work done by a force." },
  { name: "Cauchy-Schwarz Inequality", formula: "|⟨u, v⟩| ≤ ||u|| * ||v||", explanation: "The Cauchy-Schwarz inequality states that for any vectors 'u' and 'v' in an inner product space, the absolute value of the inner product of 'u' and 'v' is less than or equal to the product of the norms of 'u' and 'v'. Geometrically, it means that the magnitude of the projection of one vector onto another is less than or equal to the product of their lengths." },
];

// Function to search formulas based on user input
function searchFormulas() {
    var input, filter, ul, li, i, txtValue;
    input = document.getElementById('searchInput');
    filter = input.value.toUpperCase();
    ul = document.getElementById("searchResults");
    ul.innerHTML = ''; // Clear previous results

    formulas.forEach(function(formula) {
        if (formula.name.toUpperCase().indexOf(filter) > -1) {
            var li = document.createElement("li");
            li.innerHTML = "<h3>" + formula.name + "</h3><p>" + formula.formula + "</p><p>" + formula.explanation + "</p>";
            ul.appendChild(li);
        }
    });
}

// Call the searchFormulas function when user clicks on the search button
document.getElementById("searchButton").addEventListener("click", searchFormulas);

// Handle form submission
document.getElementById("contactForm").addEventListener("submit", function(event) {
    event.preventDefault(); // Prevent default form submission

    // Get form input values
    var name = document.getElementById("nameInput").value;
    var email = document.getElementById("emailInput").value;
    var message = document.getElementById("messageInput").value;

    // Display submitted data (you can modify this part to handle form submission as needed)
    alert("Name: " + name + "\nEmail: " + email + "\nMessage: " + message);

    // Clear form fields
    document.getElementById("nameInput").value = "";
    document.getElementById("emailInput").value = "";
    document.getElementById("messageInput").value = "";
});
